export const dynamic = "force-dynamic";
export const runtime = "nodejs";

import { NextRequest, NextResponse } from "next/server";
import jwt from "jsonwebtoken";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { prisma } from "@/lib/prisma";
import { getWorkspaceOwner } from "@/lib/workspace";

function wrapText(text: string, maxLength = 88) {
  const words = String(text || "").split(" ");
  const lines: string[] = [];
  let line = "";

  for (const word of words) {
    if ((line + " " + word).trim().length > maxLength) {
      lines.push(line.trim());
      line = word;
    } else {
      line += " " + word;
    }
  }

  if (line.trim()) lines.push(line.trim());
  return lines;
}

export async function GET(req: NextRequest, { params }: { params: { id: string } }) {
  try {
    const token = req.cookies.get("token")?.value;
    if (!token) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const decoded = jwt.verify(token, process.env.JWT_SECRET!) as { userId: string };

    const user = await prisma.user.findUnique({
      where: { id: decoded.userId },
    });

    if (!user) return NextResponse.json({ error: "User not found" }, { status: 404 });

    const workspace = await getWorkspaceOwner(user);

    if (!workspace.hasBusinessAccess) {
      return NextResponse.json({ error: "Business access required." }, { status: 403 });
    }

    const client = await prisma.client.findFirst({
      where: {
        id: params.id,
        ownerId: workspace.owner.id,
      },
      include: {
        uploads: {
          orderBy: { createdAt: "desc" },
        },
      },
    });

    if (!client) return NextResponse.json({ error: "Client not found" }, { status: 404 });

    const pdfDoc = await PDFDocument.create();
    let page = pdfDoc.addPage([595, 842]);

    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    let y = 790;

    function ensureSpace(required = 70) {
      if (y < required) {
        page = pdfDoc.addPage([595, 842]);
        y = 790;
      }
    }

    function text(value: string, size = 11, isBold = false, color = rgb(0.1, 0.1, 0.1)) {
      ensureSpace(size + 35);

      page.drawText(String(value || ""), {
        x: 50,
        y,
        size,
        font: isBold ? bold : font,
        color,
      });

      y -= size + 8;
    }

    function paragraph(value: string, size = 11) {
      for (const line of wrapText(value)) {
        text(line, size);
      }
    }

    function section(title: string) {
      y -= 10;
      text(title, 16, true, rgb(0.05, 0.1, 0.2));
      y -= 4;
    }

    const totalAudits = client.uploads.length;

    const totalSavings = client.uploads.reduce((sum, upload) => {
      const data = upload.parsedData as any;
      return sum + (Number(data?.estimated_savings) || 0);
    }, 0);

    const leakageScores = client.uploads
      .map((upload) => Number((upload.parsedData as any)?.leakage_score))
      .filter((score) => !Number.isNaN(score));

    const averageLeakage =
      leakageScores.length > 0
        ? Math.round(leakageScores.reduce((sum, score) => sum + score, 0) / leakageScores.length)
        : 0;

    const highestRisk = leakageScores.length > 0 ? Math.max(...leakageScores) : 0;

    const healthStatus =
      averageLeakage >= 70
        ? "Critical"
        : averageLeakage >= 45
          ? "Needs Attention"
          : averageLeakage >= 20
            ? "Moderate"
            : "Healthy";

    text(`${client.name} Executive Audit Portfolio`, 22, true, rgb(0.05, 0.1, 0.2));
    text("Generated by Effluxa AI", 10, false, rgb(0.35, 0.35, 0.35));
    text(`Date: ${new Date().toLocaleString()}`, 10, false, rgb(0.35, 0.35, 0.35));

    section("Client Summary");
    paragraph(
      `${client.name} has ${totalAudits} audit${totalAudits === 1 ? "" : "s"} in this workspace, ` +
      `with EUR ${totalSavings.toLocaleString()} in potential savings identified. ` +
      `Average leakage score is ${averageLeakage}/100 and highest risk score is ${highestRisk}/100. ` +
      `Client health is currently classified as ${healthStatus}.`
    );

    if (client.notes) {
      section("Client Notes");
      paragraph(client.notes);
    }

    section("Portfolio Metrics");
    text(`Total Audits: ${totalAudits}`, 12, true);
    text(`Potential Savings: EUR ${totalSavings.toLocaleString()}`, 12, true, rgb(0, 0.45, 0.15));
    text(`Average Leakage Score: ${averageLeakage}/100`, 12, true);
    text(`Highest Risk Score: ${highestRisk}/100`, 12, true);
    text(`Client Health: ${healthStatus}`, 12, true);

    section("Recent Audits");

    if (client.uploads.length === 0) {
      paragraph("No audits attached to this client yet.");
    } else {
      for (const upload of client.uploads.slice(0, 20)) {
        const data = upload.parsedData as any;

        ensureSpace(120);
        text(upload.fileUrl, 13, true, rgb(0.05, 0.1, 0.2));
        text(`Date: ${new Date(upload.createdAt).toLocaleString()}`, 10, false, rgb(0.35, 0.35, 0.35));
        text(`Leakage Score: ${data?.leakage_score ?? "N/A"}/100`, 10);
        text(`Risk Level: ${data?.risk_level || "Insufficient data"}`, 10);
        text(`Estimated Savings: EUR ${data?.estimated_savings?.toLocaleString?.() || "N/A"}`, 10);

        if (upload.internalNote) {
          paragraph(`Internal Note: ${upload.internalNote}`, 10);
        }

        y -= 8;
      }
    }

    y -= 16;
    paragraph(
      "Disclaimer: Effluxa reports are AI-generated and provided for informational purposes only. They are not financial, legal, accounting, tax, or investment advice.",
      9
    );

    const pdfBytes = await pdfDoc.save();

    return new NextResponse(Buffer.from(pdfBytes), {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="effluxa-client-${client.name.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}-portfolio.pdf"`,
      },
    });
  } catch (error) {
    console.error("CLIENT PDF EXPORT ERROR:", error);
    return NextResponse.json({ error: "Failed to export client PDF." }, { status: 500 });
  }
}
