export const dynamic = "force-dynamic";

import { prisma } from "@/lib/prisma";
import Link from "next/link";

export default async function SharedReportPage({
  params,
}: {
  params: { token: string };
}) {
  const report = await prisma.upload.findUnique({
    where: {
      shareToken: params.token,
    },
    include: {
      client: true,
    },
  });

  if (!report) {
    return (
      <div style={{ padding: "60px", fontFamily: "Arial" }}>
        <h1>Shared report not found</h1>
        <p>This link may be invalid or no longer available.</p>
      </div>
    );
  }

  const data = report.parsedData as any;

  return (
    <main
      style={{
        minHeight: "100vh",
        background: "#f8fafc",
        color: "#0f172a",
        padding: "40px 24px",
      }}
    >
      <div style={{ maxWidth: "1000px", margin: "0 auto" }}>
        <div style={{ marginBottom: "36px" }}>
          <Link href="/" style={{ fontWeight: 900, fontSize: "26px" }}>
            Eff<span style={{ color: "#2563eb" }}>luxa</span>
          </Link>
        </div>

        <div
          style={{
            background: "white",
            border: "1px solid #e2e8f0",
            borderRadius: "28px",
            padding: "36px",
            boxShadow: "0 20px 50px rgba(15,23,42,0.08)",
          }}
        >
          <h1 style={{ fontSize: "42px", fontWeight: 900 }}>
            Shared AI Financial Leak Audit
          </h1>

          <p style={{ marginTop: "12px", color: "#64748b" }}>
            File: {report.fileUrl}
          </p>

          <p style={{ marginTop: "6px", color: "#64748b" }}>
            Date: {new Date(report.createdAt).toLocaleString()}
          </p>

          {report.client && (
            <p style={{ marginTop: "6px", color: "#64748b" }}>
              Client: {report.client.name}
            </p>
          )}

          <section style={{ marginTop: "34px" }}>
            <h2>Executive Summary</h2>
            <p style={{ marginTop: "12px", lineHeight: 1.8 }}>
              {data?.executive_summary ||
                "Effluxa detected financial optimization opportunities in this document."}
            </p>
          </section>

          <section style={{ marginTop: "34px" }}>
            <h2>Leakage Score</h2>
            <div style={{ fontSize: "44px", fontWeight: 900, marginTop: "12px" }}>
              {data?.leakage_score ?? 0}/100
            </div>
          </section>

          <section style={{ marginTop: "34px" }}>
            <h2>Estimated Savings Opportunity</h2>
            <div
              style={{
                fontSize: "40px",
                fontWeight: 900,
                marginTop: "12px",
                color: "#16a34a",
              }}
            >
              €{data?.estimated_savings?.toLocaleString?.() || "N/A"}
            </div>
          </section>

          <section style={{ marginTop: "34px" }}>
            <h2>Risk Level</h2>
            <p style={{ marginTop: "12px", lineHeight: 1.8 }}>
              {data?.risk_level || "Insufficient data"} — Confidence: {data?.confidence_level || "Insufficient data"}
            </p>
          </section>

          <section style={{ marginTop: "34px" }}>
            <h2>Quick Wins</h2>
            <ul style={{ marginTop: "12px", lineHeight: 1.9 }}>
              {(data?.quick_wins || []).map((item: string, index: number) => (
                <li key={index}>{item}</li>
              ))}
            </ul>
          </section>

          <section style={{ marginTop: "34px" }}>
            <h2>Key Findings</h2>
            <ul style={{ marginTop: "12px", lineHeight: 1.9 }}>
              {(data?.key_findings || []).map((item: string, index: number) => (
                <li key={index}>{item}</li>
              ))}
            </ul>
          </section>

          <section style={{ marginTop: "34px" }}>
            <h2>AI Recommendations</h2>
            <ul style={{ marginTop: "12px", lineHeight: 1.9 }}>
              {(data?.recommendations || []).map((item: string, index: number) => (
                <li key={index}>{item}</li>
              ))}
            </ul>
          </section>

          <div
            style={{
              marginTop: "40px",
              paddingTop: "24px",
              borderTop: "1px solid #e2e8f0",
              color: "#64748b",
              fontSize: "13px",
              lineHeight: 1.7,
            }}
          >
            This shared report is AI-generated by Effluxa and provided for informational purposes only.
            It is not financial, legal, accounting, tax, or investment advice.
          </div>
        </div>
      </div>
    </main>
  );
}
