export const dynamic = "force-dynamic";

import { prisma } from "@/lib/prisma";
import Link from "next/link";

export default async function PublicClientSharePage({
  params,
}: {
  params: { token: string };
}) {
  const client = await prisma.client.findUnique({
    where: {
      shareToken: params.token,
    },
    include: {
      uploads: {
        orderBy: { createdAt: "desc" },
      },
      owner: {
        select: {
          companyName: true,
          reportFooter: true,
        },
      },
    },
  });

  if (!client) {
    return (
      <main style={{ minHeight: "100vh", padding: "48px", background: "#f8fafc", color: "#0f172a" }}>
        <h1>Client portfolio not found.</h1>
      </main>
    );
  }

  const totalAudits = client.uploads.length;

  const totalSavings = client.uploads.reduce((sum, upload) => {
    const data = upload.parsedData as any;
    return sum + (Number(data?.estimated_savings) || 0);
  }, 0);

  const leakageScores = client.uploads
    .map((upload) => Number((upload.parsedData as any)?.leakage_score))
    .filter((score) => !Number.isNaN(score));

  const averageLeakage =
    leakageScores.length > 0
      ? Math.round(leakageScores.reduce((sum, score) => sum + score, 0) / leakageScores.length)
      : 0;

  const highestRisk = leakageScores.length > 0 ? Math.max(...leakageScores) : 0;

  return (
    <main style={{ minHeight: "100vh", background: "#f8fafc", color: "#0f172a", padding: "48px 24px" }}>
      <div style={{ maxWidth: "1100px", margin: "0 auto" }}>
        <div style={{ marginBottom: "28px" }}>
          <div style={{ fontWeight: 900, fontSize: "24px" }}>
            {client.owner.companyName || "Effluxa"}
          </div>

          <p style={{ color: "#64748b", marginTop: "8px" }}>
            Shared client audit portfolio
          </p>
        </div>

        <div style={{ background: "white", borderRadius: "24px", padding: "34px", border: "1px solid #e2e8f0" }}>
          <h1 style={{ fontSize: "42px", margin: 0 }}>{client.name}</h1>

          {client.notes && (
            <p style={{ marginTop: "12px", color: "#475569", lineHeight: 1.7 }}>
              {client.notes}
            </p>
          )}
        </div>

        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))", gap: "18px", marginTop: "24px" }}>
          {[
            ["Total Audits", totalAudits],
            ["Potential Savings", `€${totalSavings.toLocaleString()}`],
            ["Average Leakage", `${averageLeakage}/100`],
            ["Highest Risk", `${highestRisk}/100`],
          ].map(([label, value]) => (
            <div key={label} style={{ background: "white", borderRadius: "20px", padding: "24px", border: "1px solid #e2e8f0" }}>
              <div style={{ color: "#64748b", fontWeight: 700 }}>{label}</div>
              <div style={{ marginTop: "12px", fontSize: "32px", fontWeight: 900 }}>{value}</div>
            </div>
          ))}
        </div>

        <div style={{ background: "white", borderRadius: "24px", padding: "30px", border: "1px solid #e2e8f0", marginTop: "24px" }}>
          <h2 style={{ margin: 0 }}>Audit History</h2>

          {client.uploads.length === 0 ? (
            <p style={{ color: "#64748b" }}>No audits attached to this client yet.</p>
          ) : (
            <div style={{ display: "grid", gap: "16px", marginTop: "22px" }}>
              {client.uploads.slice(0, 20).map((upload) => {
                const data = upload.parsedData as any;

                return (
                  <div key={upload.id} style={{ padding: "18px", borderRadius: "16px", background: "#f8fafc", border: "1px solid #e2e8f0" }}>
                    <div style={{ fontWeight: 900 }}>{upload.fileUrl}</div>
                    <div style={{ marginTop: "8px", color: "#475569" }}>
                      Leakage Score: {data?.leakage_score ?? "N/A"}/100
                    </div>
                    <div style={{ marginTop: "8px", color: "#475569" }}>
                      Estimated Savings: €{data?.estimated_savings?.toLocaleString?.() || "N/A"}
                    </div>
                    <div style={{ marginTop: "8px", color: "#64748b", fontSize: "13px" }}>
                      {new Date(upload.createdAt).toLocaleString()}
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {client.owner.reportFooter && (
          <p style={{ color: "#64748b", marginTop: "28px", lineHeight: 1.7 }}>
            {client.owner.reportFooter}
          </p>
        )}

        <p style={{ color: "#94a3b8", marginTop: "28px", fontSize: "13px" }}>
          Generated by Effluxa AI. Informational analysis only, not financial, legal, tax, accounting, or investment advice.
        </p>

        <div style={{ marginTop: "28px" }}>
          <Link href="/">
            <button style={{ padding: "14px 20px", borderRadius: "14px", border: "none", background: "#0f172a", color: "white", fontWeight: 900 }}>
              Learn more about Effluxa
            </button>
          </Link>
        </div>
      </div>
    </main>
  );
}
