export const dynamic = "force-dynamic";
export const runtime = "nodejs";

import { NextRequest, NextResponse } from "next/server";
import jwt from "jsonwebtoken";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { prisma } from "@/lib/prisma";
import { getWorkspaceOwner } from "@/lib/workspace";

function wrapText(text: string, maxLength = 88) {
  const words = String(text || "").split(" ");
  const lines: string[] = [];
  let line = "";

  for (const word of words) {
    if ((line + " " + word).trim().length > maxLength) {
      lines.push(line.trim());
      line = word;
    } else {
      line += " " + word;
    }
  }

  if (line.trim()) lines.push(line.trim());
  return lines;
}

export async function GET(req: NextRequest) {
  try {
    const token = req.cookies.get("token")?.value;
    if (!token) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const decoded = jwt.verify(token, process.env.JWT_SECRET!) as { userId: string };
    const user = await prisma.user.findUnique({ where: { id: decoded.userId } });

    if (!user) return NextResponse.json({ error: "User not found" }, { status: 404 });

    const workspace = await getWorkspaceOwner(user);

    if (!workspace.hasBusinessAccess) {
      return NextResponse.json({ error: "Agency access required." }, { status: 403 });
    }

    const reports = await prisma.upload.findMany({
      where: { userId: workspace.owner.id },
      include: { client: true },
      orderBy: { createdAt: "desc" },
    });

    const totalAudits = reports.length;

    const totalSavings = reports.reduce((sum, report) => {
      const data = report.parsedData as any;
      return sum + (Number(data?.estimated_savings) || 0);
    }, 0);

    const leakageScores = reports
      .map((report) => Number((report.parsedData as any)?.leakage_score))
      .filter((score) => !Number.isNaN(score));

    const averageLeakage =
      leakageScores.length > 0
        ? Math.round(leakageScores.reduce((sum, score) => sum + score, 0) / leakageScores.length)
        : 0;

    const highestRisk = leakageScores.length > 0 ? Math.max(...leakageScores) : 0;

    const pdfDoc = await PDFDocument.create();
    let page = pdfDoc.addPage([595, 842]);

    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    let y = 790;

    function ensureSpace(required = 70) {
      if (y < required) {
        page = pdfDoc.addPage([595, 842]);
        y = 790;
      }
    }

    function text(value: string, size = 11, isBold = false, color = rgb(0.1, 0.1, 0.1)) {
      ensureSpace(size + 35);
      page.drawText(String(value || ""), {
        x: 50,
        y,
        size,
        font: isBold ? bold : font,
        color,
      });
      y -= size + 8;
    }

    function paragraph(value: string, size = 11) {
      for (const line of wrapText(value)) text(line, size);
    }

    function section(title: string) {
      y -= 10;
      text(title, 16, true, rgb(0.05, 0.1, 0.2));
      y -= 4;
    }

    const workspaceOwner = workspace.owner as any;
    const companyName = workspaceOwner.companyName || "Effluxa";

    text(`${companyName} Workspace Executive Report`, 22, true, rgb(0.05, 0.1, 0.2));
    text("Generated by Effluxa AI", 10, false, rgb(0.35, 0.35, 0.35));
    text(`Date: ${new Date().toLocaleString()}`, 10, false, rgb(0.35, 0.35, 0.35));

    section("Executive Summary");
    paragraph(
      `This workspace contains ${totalAudits} audit${totalAudits === 1 ? "" : "s"}, ` +
        `with EUR ${totalSavings.toLocaleString()} in potential savings identified. ` +
        `Average leakage score is ${averageLeakage}/100 and the highest detected risk score is ${highestRisk}/100.`
    );

    section("Workspace Metrics");
    text(`Total Audits: ${totalAudits}`, 12, true);
    text(`Potential Savings: EUR ${totalSavings.toLocaleString()}`, 12, true, rgb(0, 0.45, 0.15));
    text(`Average Leakage Score: ${averageLeakage}/100`, 12, true);
    text(`Highest Risk Score: ${highestRisk}/100`, 12, true);

    section("Recent Audits");

    if (reports.length === 0) {
      paragraph("No audits available yet.");
    } else {
      for (const report of reports.slice(0, 30)) {
        const data = report.parsedData as any;

        ensureSpace(120);
        text(report.fileUrl, 13, true, rgb(0.05, 0.1, 0.2));
        text(`Client: ${report.client?.name || "No client"}`, 10, false, rgb(0.35, 0.35, 0.35));
        text(`Date: ${new Date(report.createdAt).toLocaleString()}`, 10, false, rgb(0.35, 0.35, 0.35));
        text(`Leakage Score: ${data?.leakage_score ?? "N/A"}/100`, 10);
        text(`Risk Level: ${data?.risk_level || "Insufficient data"}`, 10);
        text(`Estimated Savings: EUR ${data?.estimated_savings?.toLocaleString?.() || "N/A"}`, 10);

        if (report.internalNote) {
          paragraph(`Internal Note: ${report.internalNote}`, 10);
        }

        y -= 8;
      }
    }

    y -= 16;

    if (workspaceOwner.reportFooter) {
      paragraph(workspaceOwner.reportFooter, 9);
      y -= 8;
    }

    paragraph(
      "Disclaimer: Effluxa reports are AI-generated and provided for informational purposes only. They are not financial, legal, accounting, tax, or investment advice.",
      9
    );

    const pdfBytes = await pdfDoc.save();

    return new NextResponse(Buffer.from(pdfBytes), {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="effluxa-workspace-executive-report.pdf"`,
      },
    });
  } catch (error) {
    console.error("WORKSPACE PDF EXPORT ERROR:", error);
    return NextResponse.json({ error: "Failed to export workspace PDF." }, { status: 500 });
  }
}
