import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import jwt from "jsonwebtoken";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { getWorkspaceOwner } from "@/lib/workspace";
import { canAccessFullReport } from "@/lib/access";
import { asCategoryItems, asRiskItems, asTextArray, asVendorItems, getReportQualityReason, isFallbackReport } from "@/lib/reportDisplay";

export const runtime = "nodejs";

interface Props {
  params: {
    id: string;
  };
}

function wrapText(text: string, maxLength = 85) {
  const words = String(text || "").split(" ");
  const lines: string[] = [];
  let line = "";

  for (const word of words) {
    if ((line + " " + word).trim().length > maxLength) {
      lines.push(line.trim());
      line = word;
    } else {
      line += " " + word;
    }
  }

  if (line.trim()) lines.push(line.trim());
  return lines;
}

export async function GET(req: NextRequest, { params }: Props) {
  try {
    const token = req.cookies.get("token")?.value;

    if (!token) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const decoded = jwt.verify(token, process.env.JWT_SECRET!) as {
      userId: string;
    };

    const user = await prisma.user.findUnique({
      where: { id: decoded.userId },
    });

    if (!user) {
      return NextResponse.json({ error: "User not found" }, { status: 404 });
    }

    const workspace = await getWorkspaceOwner(user);

    const report = await prisma.upload.findFirst({
      where: {
        id: params.id,
        userId: workspace.owner.id,
      },
      include: {
        client: true,
      },
    });

    if (!report) {
      return NextResponse.json({ error: "Report not found" }, { status: 404 });
    }

    if (!canAccessFullReport({ report, user, workspace })) {
      return NextResponse.json({ error: "Report is locked" }, { status: 403 });
    }

    const data = report.parsedData as any;
    const isLimitedDataReport = isFallbackReport(data);
    const reportQualityReason = getReportQualityReason(data);

    const quickWins = asTextArray(data?.quick_wins, [
      "No quick wins were detected in the uploaded data.",
    ]);
    const highCostCategories = asCategoryItems(data?.high_cost_categories, [
      {
        category: "No high-cost category detected",
        amount: 0,
        reason: "The uploaded data did not contain enough category detail.",
      },
    ]);
    const duplicatePaymentRisks = asRiskItems(data?.duplicate_payment_risks, [
      {
        item: "No duplicate payment risk confirmed",
        reason: "The uploaded data did not contain enough detail to confirm duplicate payments.",
      },
    ]);
    const cashflowObservations = asTextArray(data?.cashflow_observations, [
      "Cash flow patterns could not be reliably assessed from the uploaded data.",
    ]);
    const keyFindings = asTextArray(data?.key_findings, asTextArray(data?.recommendations, [
      "No key findings were generated from the uploaded data.",
    ]));
    const topVendors = asVendorItems(data?.top_vendors, [
      {
        vendor: "No vendor data available",
        amount: 0,
        reason: "The uploaded data did not contain reliable vendor-level detail.",
      },
    ]);
    const recommendations = asTextArray(data?.recommendations, [
      "No AI recommendations were generated from the uploaded data.",
    ]);

    const pdfDoc = await PDFDocument.create();
    let page = pdfDoc.addPage([595, 842]);

    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    let y = 790;

    function ensureSpace(required = 60) {
      if (y < required) {
        page = pdfDoc.addPage([595, 842]);
        y = 790;
      }
    }

    function text(value: string, size = 11, isBold = false, color = rgb(0.1, 0.1, 0.1)) {
      ensureSpace(size + 30);

      page.drawText(String(value || ""), {
        x: 50,
        y,
        size,
        font: isBold ? bold : font,
        color,
      });

      y -= size + 8;
    }

    function section(title: string) {
      ensureSpace(90);
      y -= 8;
      text(title, 16, true, rgb(0.05, 0.1, 0.2));
      y -= 4;
    }

    function paragraph(value: string) {
      const lines = wrapText(value, 86);
      for (const line of lines) {
        text(line, 11);
      }
    }

    const workspaceOwner = workspace.owner as any;

    const title = workspaceOwner.companyName
      ? `${workspaceOwner.companyName} Financial Audit`
      : "Effluxa AI Financial Leak Audit";

    text(title, 24, true, rgb(0.05, 0.1, 0.2));
    y -= 10;

    if (workspaceOwner.companyName) {
      text("Generated by Effluxa AI", 10, false, rgb(0.35, 0.35, 0.35));
      y -= 4;
    }

    text(`File: ${report.fileUrl}`, 10, false, rgb(0.4, 0.4, 0.4));
    text(`Date: ${new Date(report.createdAt).toLocaleString()}`, 10, false, rgb(0.4, 0.4, 0.4));

    if (isLimitedDataReport) {
      y -= 8;
      text("Limited-data report", 12, true, rgb(0.75, 0.45, 0));
      paragraph(
        `This is a conservative fallback report. ${
          reportQualityReason || "The uploaded document did not support a complete structured audit."
        }`
      );
    }

    if (report.client) {
      text(`Client: ${report.client.name}`, 10, false, rgb(0.4, 0.4, 0.4));
    }

    section("Executive Summary");
    paragraph(
      data?.executive_summary ||
      "Effluxa detected financial optimization opportunities in this document."
    );

    section("Leakage Score");
    text(`${data?.leakage_score ?? 0}/100`, 18, true);

    section("Estimated Savings Opportunity");
    text(`EUR ${data?.estimated_savings?.toLocaleString?.() || "N/A"}`, 20, true, rgb(0, 0.45, 0.15));

    section("Risk Level");
    paragraph(`${data?.risk_level || "Insufficient data"} | Confidence: ${data?.confidence_level || "Insufficient data"}`);

    section("Quick Wins");
    quickWins.forEach((item: string) => paragraph(`- ${item}`));

    section("High Cost Categories");
    highCostCategories.forEach((item) => {
      paragraph(`- ${item.category} - EUR ${item.amount || 0} - ${item.reason}`);
    });

    section("Anomalies & Duplicate Payment Risks");
    (data?.anomalies || []).forEach((item: any) => paragraph(`- ${item.item || "Anomaly"} - ${item.reason || ""}`));
    duplicatePaymentRisks.forEach((item) => paragraph(`- ${item.item}${item.reason ? ` - ${item.reason}` : ""}`));

    section("Cash Flow Observations");
    cashflowObservations.forEach((item: string) => paragraph(`- ${item}`));

    section("CFO Summary");
    paragraph(data?.cfo_summary || "Insufficient data");

    section("Key Findings");
    keyFindings.forEach((item: string) => paragraph(`- ${item}`));

    section("Top Vendors");
    topVendors.forEach((vendor) => {
      paragraph(`- ${vendor.vendor} - EUR ${vendor.amount || 0}${vendor.reason ? ` - ${vendor.reason}` : ""}`);
    });

    section("AI Recommendations");
    recommendations.forEach((item: string) => paragraph(`- ${item}`));

    y -= 20;
    if (workspaceOwner.reportFooter) {
      paragraph(workspaceOwner.reportFooter);
      y -= 10;
    }

    paragraph(
      "Disclaimer: Effluxa reports are AI-generated and provided for informational purposes only. They are not financial, legal, accounting, tax, or investment advice."
    );

    const pdfBytes = await pdfDoc.save();

    return new NextResponse(Buffer.from(pdfBytes), {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="effluxa-audit-${report.id}.pdf"`,
      },
    });
  } catch (error) {
    console.error("PDF DOWNLOAD ERROR:", error);

    return NextResponse.json(
      { error: "We couldn't generate the PDF right now. Please try again." },
      { status: 500 }
    );
  }
}
